// Real project metadata, pulled from VeronicaYu_Portfolio.pdf.
// `sortDate` drives the date sort (ISO string, use the project's start date).
// `thumbFit` is "cover" for full-bleed photos or "contain" for images with transparent backgrounds.
// Single source of truth for the project gallery (projects.html) and the homepage thumbnails.
const PROJECTS = [
  // Turf Wars Claw Robot project card + detail page metadata
  {
    id: "claw-robot",
    name: "Turf Wars Claw Robot",
    dateDisplay: "January - May 2025",
    sortDate: "2025-01-01",
    type: "Class Project",
    location: "Cambridge, MA",
    skills: [
      "Mechanical Design",
      "SolidWorks",
      "CNC Milling",
      "Manual Lathing",
      "Bandsaw & Drill Press",
    ],
    thumb: "assets/images/projects/claw-robot.png",
    thumbFit: "contain",
    url: "projects/claw-robot.html",
  },
  // Wavelength project card + detail page metadata
  {
    id: "wavelength",
    name: "Wavelength",
    dateDisplay: "September 2025 - May 2026",
    sortDate: "2025-09-01",
    type: "Conflux Collective — Co-Project Lead",
    location: "Cambridge, MA",
    skills: [
      "Prototyping",
      "Mechanical Design",
      "Raspberry Pi",
      "Electronics",
      "User Testing",
    ],
    thumb: "assets/images/projects/wavelength.jpg",
    thumbFit: "cover",
    url: "projects/wavelength.html",
  },
  // Gravity-Fed Water Systems project card + detail page metadata
  {
    id: "gravity-fed-water-systems",
    name: "Gravity-Fed Water Systems",
    dateDisplay: "January 2025 - Present",
    sortDate: "2025-01-01",
    type: "Engineers Without Borders — Revit Technical Lead",
    location: "Dominican Republic & Guatemala",
    skills: [
      "Humanitarian Design",
      "International Development",
      "Revit",
      "Water Engineering",
    ],
    thumb: "assets/images/projects/gravity-fed-water-systems.jpg",
    thumbFit: "cover",
    url: "projects/gravity-fed-water-systems.html",
  },
  // Air Permeability Tester project card + detail page metadata
  {
    id: "air-permeability-tester",
    name: "Air Permeability Tester",
    dateDisplay: "December 2025 - March 2026",
    sortDate: "2025-12-01",
    type: "Research",
    location: "Cambridge, MA",
    skills: [
      "Sensor Integration",
      "Mechanical Design",
      "SolidWorks",
      "3D Printing",
      "Testing & Validation",
    ],
    thumb: "assets/images/projects/air-permeability-tester.jpg",
    thumbFit: "cover",
    url: "projects/air-permeability-tester.html",
  },
  // Rotational Fixture project card + detail page metadata
  {
    id: "rotational-fixture",
    name: "Rotational Fixture",
    dateDisplay: "March - May 2026",
    sortDate: "2026-03-01",
    type: "Research",
    location: "Cambridge, MA",
    skills: [
      "Electronics Integration",
      "MATLAB",
      "Mechanical Design",
      "SolidWorks",
      "3D Printing",
    ],
    thumb: "assets/images/projects/rotational-fixture.jpg",
    thumbFit: "cover",
    url: "projects/rotational-fixture.html",
  },
  // Python Image Tracking project card + detail page metadata
  {
    id: "python-image-tracking",
    name: "Python Image Tracking",
    dateDisplay: "June - August 2025",
    sortDate: "2025-06-01",
    type: "Bertoldi Group Research — Harvard PRISE Fellow",
    location: "Cambridge, MA",
    skills: [
      "Python",
      "OpenCV",
      "SciPy",
      "Mechanical Design",
      "SolidWorks",
      "Instron",
      "Laser Cutting",
    ],
    thumb: "assets/images/projects/python-image-tracking.jpg",
    thumbFit: "cover",
    url: "projects/python-image-tracking.html",
  },
  // Egg Drop Contraption project card + detail page metadata
  {
    id: "egg-drop-contraption",
    name: "Egg Drop Contraption",
    dateDisplay: "November - December 2025",
    sortDate: "2025-11-01",
    type: "Class Project",
    location: "Cambridge, MA",
    skills: [
      "Mechanical Design",
      "MATLAB",
      "SolidWorks",
      "3D Printing",
      "Laser Cutting",
    ],
    thumb: "assets/images/projects/egg-drop-contraption.jpg",
    thumbFit: "cover",
    url: "projects/egg-drop-contraption.html",
  },
  // Papa's Baristaria project card + detail page metadata
  {
    id: "papas-baristaria",
    name: "Papa's Baristaria",
    dateDisplay: "April - May 2026",
    sortDate: "2026-04-01",
    type: "Class Project",
    location: "Cambridge, MA",
    skills: ["Arduino", "Electronics Integration", "Circuit Debugging"],
    thumb: "assets/images/projects/papas-baristaria.jpg",
    thumbFit: "cover",
    url: "projects/papas-baristaria.html",
  },
  // Violin Workshopping project card + detail page metadata
  {
    id: "violin-workshopping",
    name: "Violin Workshopping",
    dateDisplay: "January - May 2025",
    sortDate: "2025-01-01",
    type: "Class Project",
    location: "Cambridge, MA",
    skills: ["Woodworking", "Hand Planes", "Handsaw"],
    thumb: "assets/images/projects/violin-workshopping.jpg",
    thumbFit: "cover",
    url: "projects/violin-workshopping.html",
  },
];
